### ISSUE TITLE
APIException with ApiResultListProjectVersionIssue

### ISSUE THREAD

**Issue by bard-hobson** [fortify/ssc-restapi-client#12]
I am using ssc-restapi-client-2.0 to pull information about versions to read into a json format. Usually goes well but now as of recently I am getting APIExceptions that do not produce error messages.

Code likely throwing the error as logging I put prior to the below line post but logging after it does not. 

` ApiResultListProjectVersionIssue projectVersionIssuesListResult
                            = issueOfProjectVersionControllerApi.listIssueOfProjectVersion(parentId, start, limit, q,
                                                                                           qm, orderby, filterset,
                                                                                           fields, showhidden,
                                                                                           showremoved, showsuppressed,
                                                                                           showshortfilenames, filter,
                                                                                           groupid, groupingtype);`

I cannot find any information on the web about ApiResultListProjectVersionIssue to begin tracking down the issue. 

```
Exception ExtensionDelayedRunInterceptor of SSCExtensions
com.fortify.ssc.restclient.ApiException: 
              at com.fortify.ssc.restclient.ApiClient.handleResponse(ApiClient.java:929)
              at com.fortify.ssc.restclient.ApiClient.execute(ApiClient.java:845)
              at com.fortify.ssc.restclient.api.AttributeOfProjectVersionControllerApi.listAttributeOfProjectVersionWithHttpInfo(AttributeOfProjectVersionControllerApi.java:283)
              at com.fortify.ssc.restclient.api.AttributeOfProjectVersionControllerApi.listAttributeOfProjectVersion(AttributeOfProjectVersionControllerApi.java:268)
              at cat.ssc.api.Extension.getTrouxIdsListToMatchProjectVersionsList(Extension.java:205)
              at cat.ssc.api.Extension.getVulnerabilitiesFromAppsWithTrouxIds(Extension.java:641)
              at cat.ssc.api.ExtensionDelayedRunInterceptor.afterCompletion(ExtensionDelayedRunInterceptor.java:92)
              at org.springframework.web.servlet.HandlerExecutionChain.triggerAfterCompletion(HandlerExecutionChain.java:174)
              at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1133)
              at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
              at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
              at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
              at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
              at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
              at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
              at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
              at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
              at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
              at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
              at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130)
              at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
              at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105)
              at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
              at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
              at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
              at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
              at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
              at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
              at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
              at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
              at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
              at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
              at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
              at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
              at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
              at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
              at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
              at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
              at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
              at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
              at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
              at java.lang.Thread.run(Unknown Source)

```

**Comment by akaryakina** [comment]
@bard-hobson Please, look into the ssc.log file on your Fortify SSC server (at the time of the error). The clue might come from there. I would also suggest you update to the latest version of this client.
